name: example
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0-9.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera_view:
    path: ../camera_view/camera_view
  share_plus: ^4.0.10+1

  cupertino_icons: ^1.0.2
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
