name: camera_view_windows
description: Windows implementation of the camera_view plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: camera_view
    platforms:
      windows:
        pluginClass: CameraViewWindows
        dartPluginClass: CameraViewWindows

dependencies:
  camera_view_platform_interface:
    path: ../camera_view_platform_interface
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1
