name: camera_view_android
description: Android implementation of the camera_view plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: camera_view
    platforms:
      android:
        package: com.example.verygoodcore
        pluginClass: CameraViewPlugin
        dartPluginClass: CameraViewAndroid

dependencies:
  flutter:
    sdk: flutter
  camera_view_platform_interface:
    path: ../camera_view_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^3.0.1
