name: camera_view_macos

on:
  pull_request:
    paths:
      - ".github/workflows/camera_view_macos.yaml"
      - "src/camera_view_macos/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/camera_view_macos.yaml"
      - "src/camera_view_macos/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.0.0
      working_directory: src/camera_view_macos
