name: camera_view_web
description: Web implementation of the camera_view plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: camera_view
    platforms:
      web:
        pluginClass: CameraViewWeb
        fileName: camera_view_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  camera_view_platform_interface:
    path: ../camera_view_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1
